version: '3.2'

services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_example
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${PORT}/" ]
      timeout: 3s
      retries: 3
    networks:
      - privet-net

networks:
  privet-net:
    external: true
